# Generated by Django 4.2.2 on 2024-04-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(default=None, max_length=100, null=True)),
                ('registration_number', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50, null=True)),
                ('semester', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('full_name', models.CharField(default=None, max_length=100, null=True)),
                ('employee_id', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50, null=True)),
                ('subject_taken', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField(null=True)),
                ('learner_type', models.CharField(max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slalms.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slalms.teacher')),
            ],
        ),
    ]
