# Generated by Django 4.2.2 on 2024-04-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slalms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learner_type',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='marks',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
