# Generated by Django 4.2.2 on 2024-04-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slalms', '0002_alter_course_learner_type_alter_course_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
