# Generated by Django 4.2.2 on 2024-04-08 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slalms', '0003_remove_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='marks',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
